### ISSUE TITLE
[Errors] In the gta2 manager and language options

### ISSUE THREAD

**Issue by SilentMRG** [gennariarmando/gta2-frontend-fix#10]
Hello...

First of all, I want to thank you for this BIG correction! If it weren't for your correction, I wouldn't be able to run GTA 2 at its best.

So, getting straight to the point, I'm using the Steam version and I noticed that after applying your patch I get this error when I try to access "gta2 manager.exe":

![0](https://github.com/gennariarmando/gta2-frontend-fix/assets/62117728/cc1447d3-e338-4b6e-a93a-98c7f8e471be)

Clicking "Ok" results in three consecutive "AppCrash".

The other error concerns changing the language in the game Options. The error is the following:

![1](https://github.com/gennariarmando/gta2-frontend-fix/assets/62117728/c7e9543c-5e77-403b-afe8-6819fdc4fc5f)

Clicking "Ok" does not result in any "AppCrash", however, if I then try to start the game it will not start. This will force me to delete the "settings" file from the "ufiles" folder.

These are not errors that break the gameplay, they don't bother me, as I play in English and I think that the configurator may be dismissed/ignored after applying your patch; however, I just want to inform you about these things. Other than that, the whole game works like a charm!

I want to take advantage and make a suggestion: I know I can control the character through the Mouse, and that's great! So, would it be possible to implement this feature in vehicles? Controlling vehicles with the Mouse would be perfect!

Thank you very much for your attention!

Cheers!

**Comment by gennariarmando** [comment]
The whole patch was mainly meant to ditch gta2manager.exe, ofc it won't work on it.
I'm planning to make a few updates but don't know exactly when.

Edit:
Language crashes because steam ships with english only. You need to obtain the other .gxt files in order to fix the crash, I understand I could adjust to fallback to english if no gxt is present though, I'll add this to the to-do list.

**Comment by SilentMRG** [comment]
Thank you very much for the quick response! I will be waiting for a new update. =D Your project is by far the best so far. Lots of nostalgia here, especially for these menus. GTA 2 was my first GTA and I played it to hell on the PS1. ^^

**Comment by SilentMRG** [comment]
I know this has nothing to do with your patch, but just so you know... Using the latest (as of now) version of Ultimate ASI Loader (v7.1.0) will cause "AppCrash" before the game even opens. However, when I use the "dinput.dll (v1.2.0.0)" that comes with ThirteenAG's widescreen fix everything works fine.
